## spring:
##  datasource:
    # --- PostgreSQL database
    # url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/my-app}
    # username: ${JDBC_DATABASE_USERNAME:postgres}
    # password: ${JDBC_DATABASE_PASSWORD:<<YOUR_PASSWORD>>}
    
spring:
    main:
        banner-mode: "off"
        
logging.level.org.demo.myapp.core.application.services: DEBUG